name: biorxiv
channels:
  - conda-forge
dependencies:
  - conda-forge::beautifulsoup4=4.7.1
  - conda-forge::ipykernel=4.8.2
  - conda-forge::ipywidgets=7.4.0
  - conda-forge::nb_conda_kernels=2.1.1
  - conda-forge::notebook=5.6.0
  - conda-forge::numpy=1.15.1
  - conda-forge::pandas=0.23.4
  - conda-forge::python=3.6.6
  - conda-forge::requests=2.19.1
  - conda-forge::tqdm=4.24.0
